server:
  port: 8884
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fm-soa-tx?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 1

  dubbo:
    application:
      name: soa-consumer
    registry:
      address: zookeeper://127.0.0.1:2181 #192.168.56.101:2181
    protocol:
      name: dubbo
      port: 20885
    scan: com.snill.fm
    timeout: 10000
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
      group-id: kafka2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.snill.fm.kafka.DecodeingKafka
