server:
  port: 8883

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fm-ams?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 2

  dubbo:
    application:
      name: ams-provider
    registry:
      address: zookeeper://127.0.0.1:2181 #192.168.56.101:2181
    protocol:
      name: dubbo
      port: 20883
    scan: com.snill.fm.service
    timeout: 10000