server:
  port: 8888
spring:
  dubbo:
    application:
      name: web-consumer
    registry:
      address: zookeeper://127.0.0.1:2181 #192.168.56.101:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.snill.fm
    timeout: 10000