server:
  port: 8888
spring:
  dubbo:
    application:
      name: web-consumer
    registry:
      address: zookeeper://127.0.0.1:2181 #192.168.56.101:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.snill.fm
    timeout: 10000
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
      retries: 0
      batch-size: 65536
      buffer-memory: 524288
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.snill.fm.kafka.EncodeingKafka
