server:
  port: 8882

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fm-so?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 2

  dubbo:
    application:
      name: so-provider
    registry:
      address: zookeeper://127.0.0.1:2181 #192.168.56.101:2181
    protocol:
      name: dubbo
      port: 20882
    scan: com.snill.fm.service
    timeout: 10000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    #主从配置
    #name of Redis server  哨兵监听的Redis server的名称
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26378,127.0.0.1:26377
  session:
    store-type: none